const regiones = [
    "WWF GLOBAL",
    "ADRIA",
    "ARGENTINA",
    "ARMENIA",
    "ASIAPACIFIC",
    "AUSTRALIA",
    "AUSTRIA",
    "AZERBAIJAN",
    "BELGIUM",
    "BHUTAN",
    "BOLIVIA",
    "BORNEO",
    "BRAZIL",
    "BULGARIA",
    "CAMBODIA",
    "CAMEROON",
    "CANADA",
    "CAUCASUS",
    "CENTRAL AFRICAN REPUBLIC",
    "CENTRAL AMERICA",
    "CHILE",
    "CHINA",
    "COLOMBIA",
    "CROATIA",
    "DEMOCRATIC REPUBLIC OF THE CONGO",
    "DENMARK",
    "ECUADOR",
    "EUROPEAN POLICY OFFICE",
    "FINLAND",
    "FRANCE",
    "GABON",
    "GERMANY",
    "GREATER MEKONG",
    "GREECE",
    "GUIANAS",
    "HONG KONG SAR",
    "HUNGARY",
    "INDIA",
    "INDONESIA",
    "ITALY",
    "JAPAN",
    "KENYA",
    "KOREA",
    "LAOS",
    "LATVIA",
    "MADAGASCAR",
    "MALAYSIA",
    "MEDITERRANEAN",
    "MEXICO",
    "MONGOLIA",
    "MOZAMBIQUE",
    "MYANMAR",
    "NAMIBIA",
    "NEPAL",
    "NETHERLANDS",
    "NEW ZEALAND",
    "NORWAY",
    "PAKISTAN",
    "PAPUA NEW GUINEA",
    "PARAGUAY",
    "PERU",
    "PHILIPPINES",
    "POLAND",
    "PORTUGAL",
    "REGIONAL OFFICE AFRICA",
    "ROMANIA",
    "SENEGAL",
    "SERBIA",
    "SINGAPORE",
    "SLOVAKIA",
    "SLOVENIA",
    "SOUTH AFRICA",
    "SOUTH PACIFIC"
];
  
export default (req, res) => {
    res.status(200).json({ regiones });
};